### ISSUE TITLE
Admin: javascript error: "You must bind Parsley on an existing element." / update parsley

### ISSUE THREAD

**Issue by blueyed** [agiliq/Django-parsley#43]
I have experimented with using django-parsley in the admin with Django 1.6.

I am seeing the error "You must bind Parsley on an existing element." in the Firefox console.

This appears to get triggered via the following code from parsley.js:

    if (false !== ParsleyUtils.get(window, 'ParsleyConfig.autoBind'))
      $(document).ready(function () {
        // Works only on `data-parsley-validate`.
        $('[data-parsley-validate]').parsley();

I have then tried setting `ParsleyConfig.autoBind = false`, but there appears to be a problem with `ParsleyUtils.get`, which returns undefined for `false`.

This appears to be fixed in Parsley 2.0.2.

Also, `parsley()` is only called in 2.0.2 automatically, if matching elements have been found:

    if (false !== ParsleyUtils.get(window, 'ParsleyConfig.autoBind'))
      $(document).ready(function () {
        // Works only on `data-parsley-validate`.
        if ($('[data-parsley-validate]').length)
          $('[data-parsley-validate]').parsley();
      });

Given this, and that there are probably more bug fixes in the latest parsley release, it should get updated with django-parsley.

I will provide a pull request for this.

**Comment by brunowego** [comment]
:+1:

**Comment by akshar-raaj** [comment]
@blueyed Can we close this?
