### ISSUE TITLE
RegexField with parsley 2.x

### ISSUE THREAD

**Issue by rzanluchi** [agiliq/Django-parsley#46]
Hi,

I noticed that you upgraded to parsley 2.x but haven't upgraded the regex parsley attribute https://github.com/agiliq/Django-parsley/blob/master/parsley/decorators.py#L38
Parsley 2.x uses a different  attribute name for regex fields: 'data-parsley-pattern'

Thanks

**Comment by 9dev** [comment]
I noticed the same thing.
+1

**Comment by akshar-raaj** [comment]
@rzanluchi @9dev Fixed in https://github.com/agiliq/Django-parsley/commit/84d3322c6d3be84349e76e0e6a6aae5a9943d35b
