### ISSUE TITLE
Custom Error on form field?

### ISSUE THREAD

**Issue by deronsizemore** [agiliq/Django-parsley#54]
I've got a form field which parsley validates correctly but returns "this field is required." I'm attempting to return my own custom error message for this field and I have this in my Meta class in the forms.py:

        parsley_extras = {
            'category': {
                'error-message': 'Category is required.',
            },
        }

Can someone tell me what I'm doing wrong?

**Comment by akshar-raaj** [comment]
@deronsizemore For your use case, you don't require parsley_extras.

You can use Django's `error_messages` on your form field and then Django-parsley will do the right thing to add `data-parsley-required-message` on the rendered field. And then parsley.js will use data-parsley-required-message correctly.

Your form should look like:

    class TextForm(forms.Form):
    "A simple form"
        name = forms.CharField(required=True, error_messages={'required': 'Name must be there'})
        university = forms.CharField(required=False)

When you do this, parsley will say "Name must be there" when your field doesn't validate.

**Comment by deronsizemore** [comment]
Thanks for the reply @akshar-raaj. Sorry, I probably should have been more clear with my setup. My category field is a field inside of my form, but I'm generating data inside that field in the view that loads that page. 

For example, if not a request.method == POST, then I have:

    form.fields['category'].queryset = Category.objects.order_by('name').filter(hidden=False).exclude(name="Giveaways")

That is what loads the data into my dropdown for the category field.

I'm not sure if I can remove this line from my view and do something like what you posted above? I guess I've never queried data and created a field like this in my forms.py before. Sorry, I'm still learning. Could you offer any more guidance here on how to accomplish what I'm attempting?

**Comment by akshar-raaj** [comment]
@deronsizemore Yeah, but you would still be having your form in forms.py like this

    # forms.py
    class MyForm(forms.ModelForm):
        category = forms.ModelChoiceField(required=True)
        class Meta:
            model = MyModel

So, why can't you have this line in your field

    category = forms.ModelChoiceField(required=True, error_messages={'required': 'Category must be there'})

**Comment by deronsizemore** [comment]
Ah, thanks for that @akshar-raaj. Seems I'm still learning something new every day. Just was ignorant to the fact that I could use a ModelChoiceField and then pass a queryset to it to generate the data for the select box on the front end. I ended up doing this:

	category = forms.ModelChoiceField(queryset=Category.objects.order_by('name').filter(hidden=False).exclude(name="Giveaways"), required=True, error_messages={'required': 'Category is required.'})

And it works like a charm. Thanks again!
