### ISSUE TITLE
Problem with select fields attributes generation in django admin

### ISSUE THREAD

**Issue by aaboffill** [agiliq/Django-parsley#55]
I'm starting with django-parsley, it's a very nice app to develop django projects.  It's very easy to configure and to use. But I have a problem using django-parsley to generate the client parsley validation in the django admin, I have this bug with django 1.6.1 and 1.6.7. The problem is related with select field parsley generation, all input fields are generated correctly, and  the parsley.js validation works fine, but the data-parsley attribute of the select fields are missing.
I debugged for long time the django source and the html tags generated for the select fields don't contain the data-parsley attributes.
For now, I'm not using django-parsely for the django admin in my applications because not all fields are validated correctly.
I've searched online and I can't find any other developer comment regarding this problem. If anybody have this problem, or is able to find the solution, I'll be happy to use it.

**Comment by akshar-raaj** [comment]
@aaboffill Which attribute of select field is missing?

I tested the following with Django 1.6 and it seems to work for me:

### First test using "python manage.py shell"

    from parsley.tests.forms import FormWithCustomChoices
    f = FormWithCustomChoices()
    print f.as_ul()

#### Output

    <li><label for="id_state">State:</label> <select data-parsley-required="true" data-parsley-required-message="This field is required." id="id_state" name="state">
    <option value="NY">NY</option>
    <option value="OH">OH</option>
    </select></li>

So you can see that data-parsley attributes are there

### Second test in admin

I created a model in example/core/models.py

    class SelectModel(models.Model):
    choices = models.CharField(choices=[("1", "1"), ("2", "2")], max_length=1)

I created a ModelAdmin for this in example/core/admin.py

    class SelectAdmin(ParsleyAdminMixin, admin.ModelAdmin):

        class Meta:
            model = SelectModel

        class Media:
            js = (
            "//code.jquery.com/jquery-latest.min.js",
            "parsley/js/parsley.min.js",
            "parsley/js/parsley.django-admin.js"
            )

    admin.site.register(SelectModel, SelectAdmin)

At http://localhost:8000/admin/core/selectmodel/add/, if I try to "Save" the form without selecting a choice, then parsley.js correctly raises an error "This field is required."
