### ISSUE TITLE
type error message changed to data-parsley-type-message in parsley 2.x

### ISSUE THREAD

**Issue by blue-o** [agiliq/Django-parsley#56]
I have noticed the change made in parsley 2.x in regard to type errors from data-parsley-'specific type'-message to the general type error message, data-parsley-type-message, but there is no adjustment in django-parsley. I wonder when this will be reflected. 

Cheers.

**Comment by shivakrshn49** [comment]
@blue-o Can you share a link that you noticed the change ?

**Comment by blue-o** [comment]
I haven't got it with me just now, but If you test it with
data-parsley-email-message in html, you will be able to see the error
message is not showing up. If you change that to
data-parsley-error-message, the general error message, you'll be seeing it.

I hope this will help.

**Comment by akshar-raaj** [comment]
Parsley.js 1.x behaviour:

    <input type="text" name="number" parsley-type="number" parsley-type-number-message="Missing Number"/>

In parsley.js 2.x, the equivalent of above would be

    <input type="text" name="number" data-parsley-type="number" data-parsley-type-message="Missing Number"/>

I assume this is what @blue-o wants reflected in Django-parsley.

**Comment by akshar-raaj** [comment]
@blue-o The change you asked for has been implemented here

https://github.com/agiliq/Django-parsley/commit/863e3f40518801c63b77defa293132cff46b226a

It's merged to master now.
