### ISSUE TITLE
Upload 0.7 to pypi?

### ISSUE THREAD

**Issue by clokep** [agiliq/Django-parsley#83]
Hi! First, thanks for making django-parsley! It seems that version 0.7 of django-parsley was released (https://github.com/agiliq/Django-parsley/releases/tag/v0.7), but it isn't available on pypi (`pip install django-parsley==0.7` fails): https://pypi.org/project/django-parsley/#history. Would it be possible to get this version uploaded to pypi?

Thanks!

**Comment by jansegre** [comment]
I've also noticed this but forgot to open an issue, came back to see if it was published. Currently using this on my `setup.py`:

```python
setup(
    # ...
    dependency_links=[
        'git+https://github.com/agiliq/Django-parsley@v0.7#egg=django-parsley-0.7',
    ],
    # ...
)
```

Which is not ideal at all becuase it requires using `--process-dependency-links` when `pip install`ing and that's deprecated:

```DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.```

**Comment by jproffitt** [comment]
Hi, thanks for reporting this. I have been added as a maintainer to this repo, and I have done the work to create version 0.7.

Unfortunately the original maintainers have not been responsive about publishing to PyPi. I have emailed them several times asking for them to either give me permission to publish myself, or for them to publish themselves.

At this point, I am wondering if I should create a new package on PyPi as they do not seem willing to maintain or change ownership of the PyPi project.

**Comment by jansegre** [comment]
Well, I wouldn't mind if the package changed name. That may even be done temporarily, but it has implications of course. Maybe setting a deadline can help decide, like one or two months.

**Comment by clokep** [comment]
I believe you can request that pypi change the ownership of a package as well, but I'm unsure of what "proof" you need to offer!

Regardless, thanks for picking up maintaining this package!

**Comment by jproffitt** [comment]
Well, it has been almost a month since my last comment. Still no word from the maintainers even though I have emailed them again once or twice since them. @clokep I have looked for a way to request a change of ownership, but I can't seem to find how to do that. Could you let me know if you know how?

**Comment by clokep** [comment]
The best I could find were https://stackoverflow.com/questions/45935230/transfer-ownership-of-pypi-packages and https://www.python.org/dev/peps/pep-0541/, but that's still in Draft status...so not sure really.

**Comment by akshar-raaj** [comment]
@clokep @jansegre @jproffitt Please accept my sincere apologies about the unresponsiveness on this issue.

I have uploaded it to Pypi now.

https://pypi.org/project/django-parsley/#history

**Comment by clokep** [comment]
Awesome! Thanks for uploading this. I'm going to close this.
