### ISSUE TITLE
Validations not runned before save

### ISSUE THREAD

**Issue by Matthijsy** [agiliq/Django-parsley#91]
We would like to use parsley to do client side form validation in our django admin interface. This works quite well. However, we have to click to submit button before the validations are runned. This is probably because the trigger is set to false (https://github.com/agiliq/Django-parsley/blob/master/parsley/static/parsley/js/parsley.js#L131). Is it possible to change this trigger to 'change' in some way, without modifying the static files?

Would be really great to hear from you

**Comment by ak4zh** [comment]
All these options could be overriden and specified directly in DOM using `data-parsley-` default DOM-API

Following script will trigger the validation on input, focusin and focusout

```
<script type="text/javascript">$('form').parsley({
    trigger: "focusin focusout input",
});</script>
```

Refrence: https://parsleyjs.org/doc/

**Comment by Matthijsy** [comment]
Thanks for clarifying! I am not sure anymore where I used it, so I cannot verify that it really works. Since the functionality is already there I will close this issue.
